export const cardTopContainer: string;
export const cardTop: string;
export const nameContainer: string;
export const nextToNameContainer: string;
export const name: string;
export const label: string;
export const edge: string;
export const alignment: string;
export const challenge: string;
