export enum ClassesToHitDiceTypeEnum {
    BARBARIAN = 12,
    BARD = 8,
    CLERIC = 8,
    DRUID = 8,
    FIGHTER = 10,
    MONK = 8,
    PALADIN = 10,
    RANGER = 10,
    ROGUE = 8,
    SORCERER = 6,
    WARLOCK = 8,
    WIZARD = 6,
    ARTIFICER = 8,
    NONE = 0,
}